Updated Mac nightly script. Now with clean!
git-svn-id: http://svn.berlios.de/svnroot/repos/oolite-linux/trunk@3934 127b21dd-08f5-0310-b4b7-95ae10353056

diff --git a/tools/nightly-build/mac/build-nightly b/tools/nightly-build/mac/build-nightly
--- a/tools/nightly-build/mac/build-nightly
+++ b/tools/nightly-build/mac/build-nightly
@@ -35,6 +35,7 @@ DOCKTILE_PKG_DST=$OOLITE_APP_PKG/Contents/PlugIns
 
 FTP_URL_FILE=../config/ftp_url
 FTP_CREDENTIALS_FILE=../config/ftp_credentials
+FTP_INFO_SET=0
 
 
 function report
@@ -60,23 +61,31 @@ function fail
 
 if [ ! -e $REPO_DIR_NAME ]
 then
-#	# Check out repo if necessary.
-#	CLEAN_CHECKOUT=1
-#	
-#	echo "Checking out Oolite..."
-#	svn checkout --quiet svn://svn.berlios.de/oolite-linux/trunk $REPO_DIR_NAME
-#	if [ ! $? ]
-#	then
-#		fail "Failed to check out."
-#	fi
-#	
-#	if [ -e $REPO_DIR_NAME/$LAST_REVISION_FILE ]
-#	then
-#		rm $REPO_DIR_NAME/$LAST_REVISION_FILE
-#	fi
+	# Check out repo if necessary.
+	CLEAN_CHECKOUT=1
 	
-	# Can't actually automate checkout because of the need for libpng sources.
-	fail "No $REPO_DIR_NAME checkout found!"
+	echo "Checking out Oolite..."
+	svn checkout --quiet svn://svn.berlios.de/oolite-linux/trunk $REPO_DIR_NAME
+	if [ ! $? ]
+	then
+		fail "Failed to check out."
+	fi
+	
+	if [ -e $REPO_DIR_NAME/$LAST_REVISION_FILE ]
+	then
+		rm $REPO_DIR_NAME/$LAST_REVISION_FILE
+	fi
+	
+	# Run update-mozilla script up front so there's a bit of feedback.
+	pushd $REPO_DIR_NAME/deps/Cocoa-deps/scripts > /dev/null
+	./update-mozilla.sh
+	UPDATE_RESULT=$1
+	popd > /dev/null
+	
+	if [ ! $UPDATE_RESULT ]
+	then
+		exit 1
+	fi
 else
 	CLEAN_CHECKOUT=0
 fi
@@ -177,7 +186,7 @@ fi
 echo "SNAPSHOT_MACROS= -DSNAPSHOT_BUILD=1 -DOOLITE_SNAPSHOT_VERSION=\"\\\"$OOLITE_VERSION-$CURRENT_REVISION\\\"\"" > src/Cocoa/oolite-snapshot.xcconfig
 
 # Buildez la vache!
-xcodebuild -project Oolite.xcodeproj -target "Build All" -configuration $CONFIGURATION RUN_CLANG_STATIC_ANALYZER=NO >$STDOUT_FILE 2>$STDERR_FILE
+xcodebuild clean build -project Oolite.xcodeproj -target "Build All" -configuration $CONFIGURATION RUN_CLANG_STATIC_ANALYZER=NO >$STDOUT_FILE 2>$STDERR_FILE
 
 # Generate status and diagnostics files. The -mlong-branch bit filters out
 # an unimportant warning generated by a bug in the 10.4 SDK for Xcode 3.2.
@@ -222,7 +231,7 @@ cp -R $LOG $LOG_SUCCESS
 
 # Build dock tile plug-in.
 echo "Building dock tile plug-in..."
-xcodebuild -project Mac-specific/Oolite-docktile/Oolite-docktile.xcodeproj -configuration $CONFIGURATION RUN_CLANG_STATIC_ANALYZER=NO >>$DOCKTILE_STDOUT_FILE 2>>$STDERR_FILE
+xcodebuild clean build -project Mac-specific/Oolite-docktile/Oolite-docktile.xcodeproj -configuration $CONFIGURATION RUN_CLANG_STATIC_ANALYZER=NO >>$DOCKTILE_STDOUT_FILE 2>>$STDERR_FILE
 
 grep "^[^\ ]" $DOCKTILE_STDOUT_FILE > $DOCKTILE_STATUS_FILE
 grep -e "warning:" -e "error:" $STDOUT_FILE > $DOCKTILE_DIAGNOSTICS_FILE
@@ -232,7 +241,10 @@ grep -e "^\*\* BUILD FAILED \*\*$" $STDERR_FILE
 if [ $? -eq 1 ]
 then
 	# Success, move into place.
-	mkdir $DOCKTILE_PKG_DST
+	if [ ! -d $DOCKTILE_PKG_DST ]
+	then
+		mkdir $DOCKTILE_PKG_DST
+	fi
 	mv $DOCKTILE_PKG $DOCKTILE_PKG_DST
 fi
 
