Updated Mac nightly build script to include dock tile plug-in for Snow Leopard.
git-svn-id: http://svn.berlios.de/svnroot/repos/oolite-linux/trunk@3538 127b21dd-08f5-0310-b4b7-95ae10353056

diff --git a/tools/nightly-build/mac/build-nightly b/tools/nightly-build/mac/build-nightly
--- a/tools/nightly-build/mac/build-nightly
+++ b/tools/nightly-build/mac/build-nightly
@@ -21,10 +21,18 @@ DIAGNOSTICS_FILE=$LOG/diagnostics
 STDERR_FILE=$LOG/xcb_stderr.txt
 STDOUT_FILE=$LOG/xcb_stdout.txt
 STATUS_FILE=$LOG/build_log
+DOCKTILE_STDOUT_FILE=$LOG/xcb_stdout_docktile.txt
+DOCKTILE_DIAGNOSTICS_FILE=$LOG/diagnostics_docktile
+DOCKTILE_STATUS_FILE=$LOG/build_log_docktile
 SVNUP_FILE=$LOG/svnup.txt
 LAST_UPDATED_FILE="$VAR/last_updated"
+DOCKTILE_NAME=Oolite.docktileplugin
+
 OOLITE_APP_PKG=$BUILD_DIR/Oolite.app
 DEBUG_OXP_PKG=$BUILD_DIR/Debug.oxp
+DOCKTILE_PKG=$BUILD_DIR/$DOCKTILE_NAME
+DOCKTILE_PKG_DST=$OOLITE_APP_PKG/Contents/PlugIns
+
 FTP_URL_FILE=../config/ftp_url
 FTP_CREDENTIALS_FILE=../config/ftp_credentials
 
@@ -210,6 +218,23 @@ then
 	rm -rf $LOG_SUCCESS
 fi
 cp -R $LOG $LOG_SUCCESS
+
+
+# Build dock tile plug-in.
+echo "Building dock tile plug-in..."
+xcodebuild -project Mac-specific/Oolite-docktile/Oolite-docktile.xcodeproj -configuration $CONFIGURATION RUN_CLANG_STATIC_ANALYZER=NO >>$DOCKTILE_STDOUT_FILE 2>>$STDERR_FILE
+
+grep "^[^\ ]" $DOCKTILE_STDOUT_FILE > $DOCKTILE_STATUS_FILE
+grep -e "warning:" -e "error:" $STDOUT_FILE > $DOCKTILE_DIAGNOSTICS_FILE
+
+#Check for failure.
+grep -e "^\*\* BUILD FAILED \*\*$" $STDERR_FILE
+if [ $? -eq 1 ]
+then
+	# Success, move into place.
+	mkdir $DOCKTILE_PKG_DST
+	mv $DOCKTILE_PKG $DOCKTILE_PKG_DST
+fi
 
 
 # Pack up a zip file.
