improve svn error handling in the nightly build script
git-svn-id: http://svn.berlios.de/svnroot/repos/oolite-linux/trunk@324 127b21dd-08f5-0310-b4b7-95ae10353056

diff --git a/tools/mknightly b/tools/mknightly
--- a/tools/mknightly
+++ b/tools/mknightly
@@ -33,13 +33,24 @@ then
 fi
 
 svn up >/dev/null 
+if [ $? != 0 ]
+then
+   echo "Nightly build could not svn up"
+   exit 255
+fi
 
 # check whether we should even bother building
 LASTBUILD=`cat LASTBUILD` 
 THISBUILD=`svn info . | grep Revision | cut -d ' ' -f 2`
+if [ $? != 0 ]
+then
+   echo "Could not get build revision"
+   exit 255
+fi
+
 if [ "$LASTBUILD" == "$THISBUILD" ]
 then
-   echo "Debug: Up to date - lastbuild=$LASTBUILD thisbuild=$THISBUILD"
+   echo "Nightly build up to date - lastbuild=$LASTBUILD thisbuild=$THISBUILD"
    exit 0
 fi
 
